// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/cidr.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CIDR pairs an IP with a Subnet. The IP's family determines the
// valid prefix-length range on Subnet (0..32 for v4, 0..128 for v6).
type CIDR struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            *IP                    `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Subnet        *Subnet                `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CIDR) Reset() {
	*x = CIDR{}
	mi := &file_proto_ippb_cidr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CIDR) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIDR) ProtoMessage() {}

func (x *CIDR) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_cidr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIDR.ProtoReflect.Descriptor instead.
func (*CIDR) Descriptor() ([]byte, []int) {
	return file_proto_ippb_cidr_proto_rawDescGZIP(), []int{0}
}

func (x *CIDR) GetIp() *IP {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *CIDR) GetSubnet() *Subnet {
	if x != nil {
		return x.Subnet
	}
	return nil
}

var File_proto_ippb_cidr_proto protoreflect.FileDescriptor

const file_proto_ippb_cidr_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ippb/cidr.proto\x12\x02ip\x1a\x13proto/ippb/ip.proto\x1a\x17proto/ippb/subnet.proto\"B\n" +
	"\x04CIDR\x12\x16\n" +
	"\x02ip\x18\x01 \x01(\v2\x06.ip.IPR\x02ip\x12\"\n" +
	"\x06subnet\x18\x02 \x01(\v2\n" +
	".ip.SubnetR\x06subnetB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_cidr_proto_rawDescOnce sync.Once
	file_proto_ippb_cidr_proto_rawDescData []byte
)

func file_proto_ippb_cidr_proto_rawDescGZIP() []byte {
	file_proto_ippb_cidr_proto_rawDescOnce.Do(func() {
		file_proto_ippb_cidr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_cidr_proto_rawDesc), len(file_proto_ippb_cidr_proto_rawDesc)))
	})
	return file_proto_ippb_cidr_proto_rawDescData
}

var file_proto_ippb_cidr_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ippb_cidr_proto_goTypes = []any{
	(*CIDR)(nil),   // 0: ip.CIDR
	(*IP)(nil),     // 1: ip.IP
	(*Subnet)(nil), // 2: ip.Subnet
}
var file_proto_ippb_cidr_proto_depIdxs = []int32{
	1, // 0: ip.CIDR.ip:type_name -> ip.IP
	2, // 1: ip.CIDR.subnet:type_name -> ip.Subnet
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ippb_cidr_proto_init() }
func file_proto_ippb_cidr_proto_init() {
	if File_proto_ippb_cidr_proto != nil {
		return
	}
	file_proto_ippb_ip_proto_init()
	file_proto_ippb_subnet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_cidr_proto_rawDesc), len(file_proto_ippb_cidr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ippb_cidr_proto_goTypes,
		DependencyIndexes: file_proto_ippb_cidr_proto_depIdxs,
		MessageInfos:      file_proto_ippb_cidr_proto_msgTypes,
	}.Build()
	File_proto_ippb_cidr_proto = out.File
	file_proto_ippb_cidr_proto_goTypes = nil
	file_proto_ippb_cidr_proto_depIdxs = nil
}
