// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/geo.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GeoSource identifies which data source produced a geolocation result.
// proto-ip combines authoritative-but-coarse self-published geofeeds with
// the coordinate-bearing DB-IP City Lite database.
type GeoSource int32

const (
	GeoSource_GEO_SOURCE_UNKNOWN GeoSource = 0
	// RFC 8805 geofeed, discovered per RFC 9632 (self-published by the
	// network operator; high trust, but no coordinates).
	GeoSource_GEO_SOURCE_GEOFEED GeoSource = 1
	// DB-IP City Lite (CC BY 4.0). Aggregated estimate; carries lat/lon.
	GeoSource_GEO_SOURCE_DBIP_LITE GeoSource = 2
	// RIPE IPmap (RIPE NCC ToS). Measured geolocation of core Internet
	// infrastructure (routers, IXPs); exact-IP, carries lat/lon.
	GeoSource_GEO_SOURCE_IPMAP GeoSource = 3
	// IP2Location LITE DB5 (CC BY-SA 4.0). Optional, opt-in whole-space
	// estimate from CSV; carries lat/lon. Aggregated like DB-IP.
	GeoSource_GEO_SOURCE_IP2LOCATION_LITE GeoSource = 4
	// iptoasn.com (RouteViews/RIS BGP-derived, PDDL/public domain). Provides
	// origin ASN + a country floor (no coordinates).
	GeoSource_GEO_SOURCE_IPTOASN GeoSource = 5
)

// Enum value maps for GeoSource.
var (
	GeoSource_name = map[int32]string{
		0: "GEO_SOURCE_UNKNOWN",
		1: "GEO_SOURCE_GEOFEED",
		2: "GEO_SOURCE_DBIP_LITE",
		3: "GEO_SOURCE_IPMAP",
		4: "GEO_SOURCE_IP2LOCATION_LITE",
		5: "GEO_SOURCE_IPTOASN",
	}
	GeoSource_value = map[string]int32{
		"GEO_SOURCE_UNKNOWN":          0,
		"GEO_SOURCE_GEOFEED":          1,
		"GEO_SOURCE_DBIP_LITE":        2,
		"GEO_SOURCE_IPMAP":            3,
		"GEO_SOURCE_IP2LOCATION_LITE": 4,
		"GEO_SOURCE_IPTOASN":          5,
	}
)

func (x GeoSource) Enum() *GeoSource {
	p := new(GeoSource)
	*p = x
	return p
}

func (x GeoSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoSource) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_geo_proto_enumTypes[0].Descriptor()
}

func (GeoSource) Type() protoreflect.EnumType {
	return &file_proto_ippb_geo_proto_enumTypes[0]
}

func (x GeoSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoSource.Descriptor instead.
func (GeoSource) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{0}
}

// GeoConfidence is a coarse trust level for a location estimate. It is a
// separate axis from granularity: a country may be high-confidence while a
// city is low. Measured (IPmap) and self-published (geofeed) data rate HIGH;
// aggregated estimate DBs rate MEDIUM; coarse BGP-derived country floors rate
// LOW; and any address in a known anycast prefix is forced to LOW because a
// single physical location is not meaningful there.
type GeoConfidence int32

const (
	GeoConfidence_GEO_CONFIDENCE_UNKNOWN GeoConfidence = 0
	GeoConfidence_GEO_CONFIDENCE_LOW     GeoConfidence = 1
	GeoConfidence_GEO_CONFIDENCE_MEDIUM  GeoConfidence = 2
	GeoConfidence_GEO_CONFIDENCE_HIGH    GeoConfidence = 3
)

// Enum value maps for GeoConfidence.
var (
	GeoConfidence_name = map[int32]string{
		0: "GEO_CONFIDENCE_UNKNOWN",
		1: "GEO_CONFIDENCE_LOW",
		2: "GEO_CONFIDENCE_MEDIUM",
		3: "GEO_CONFIDENCE_HIGH",
	}
	GeoConfidence_value = map[string]int32{
		"GEO_CONFIDENCE_UNKNOWN": 0,
		"GEO_CONFIDENCE_LOW":     1,
		"GEO_CONFIDENCE_MEDIUM":  2,
		"GEO_CONFIDENCE_HIGH":    3,
	}
)

func (x GeoConfidence) Enum() *GeoConfidence {
	p := new(GeoConfidence)
	*p = x
	return p
}

func (x GeoConfidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoConfidence) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_geo_proto_enumTypes[1].Descriptor()
}

func (GeoConfidence) Type() protoreflect.EnumType {
	return &file_proto_ippb_geo_proto_enumTypes[1]
}

func (x GeoConfidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoConfidence.Descriptor instead.
func (GeoConfidence) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{1}
}

// GeoGranularity ranks how specific a location is, so the merge logic can
// pick the most precise result available. COORDINATES is the finest.
type GeoGranularity int32

const (
	GeoGranularity_GEO_GRANULARITY_UNKNOWN     GeoGranularity = 0
	GeoGranularity_GEO_GRANULARITY_COUNTRY     GeoGranularity = 1
	GeoGranularity_GEO_GRANULARITY_REGION      GeoGranularity = 2
	GeoGranularity_GEO_GRANULARITY_CITY        GeoGranularity = 3
	GeoGranularity_GEO_GRANULARITY_COORDINATES GeoGranularity = 4
)

// Enum value maps for GeoGranularity.
var (
	GeoGranularity_name = map[int32]string{
		0: "GEO_GRANULARITY_UNKNOWN",
		1: "GEO_GRANULARITY_COUNTRY",
		2: "GEO_GRANULARITY_REGION",
		3: "GEO_GRANULARITY_CITY",
		4: "GEO_GRANULARITY_COORDINATES",
	}
	GeoGranularity_value = map[string]int32{
		"GEO_GRANULARITY_UNKNOWN":     0,
		"GEO_GRANULARITY_COUNTRY":     1,
		"GEO_GRANULARITY_REGION":      2,
		"GEO_GRANULARITY_CITY":        3,
		"GEO_GRANULARITY_COORDINATES": 4,
	}
)

func (x GeoGranularity) Enum() *GeoGranularity {
	p := new(GeoGranularity)
	*p = x
	return p
}

func (x GeoGranularity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoGranularity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_geo_proto_enumTypes[2].Descriptor()
}

func (GeoGranularity) Type() protoreflect.EnumType {
	return &file_proto_ippb_geo_proto_enumTypes[2]
}

func (x GeoGranularity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoGranularity.Descriptor instead.
func (GeoGranularity) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{2}
}

// GeoLocation is a single physical-location estimate for an IP address.
// Coordinates are optional so a present "0,0" is distinguishable from
// "no coordinates available" (geofeeds never carry coordinates).
type GeoLocation struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Latitude  *float64               `protobuf:"fixed64,1,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude *float64               `protobuf:"fixed64,2,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	// ISO 3166-1 alpha-2 country code (e.g. "US").
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// ISO 3166-2 region/subdivision code (e.g. "US-CA").
	Region     string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	City       string `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	PostalCode string `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	// IANA time zone (e.g. "America/Los_Angeles") when the source provides it.
	TimeZone      string         `protobuf:"bytes,7,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`
	Granularity   GeoGranularity `protobuf:"varint,8,opt,name=granularity,proto3,enum=ip.GeoGranularity" json:"granularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoLocation) Reset() {
	*x = GeoLocation{}
	mi := &file_proto_ippb_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoLocation) ProtoMessage() {}

func (x *GeoLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoLocation.ProtoReflect.Descriptor instead.
func (*GeoLocation) Descriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{0}
}

func (x *GeoLocation) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *GeoLocation) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *GeoLocation) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *GeoLocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GeoLocation) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeoLocation) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *GeoLocation) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *GeoLocation) GetGranularity() GeoGranularity {
	if x != nil {
		return x.Granularity
	}
	return GeoGranularity_GEO_GRANULARITY_UNKNOWN
}

// GeoSourceResult is one source's answer for a query, with provenance.
type GeoSourceResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Source   GeoSource              `protobuf:"varint,1,opt,name=source,proto3,enum=ip.GeoSource" json:"source,omitempty"`
	Location *GeoLocation           `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// The CIDR prefix the matched record applies to (e.g. "8.8.8.0/24").
	MatchedPrefix string `protobuf:"bytes,3,opt,name=matched_prefix,json=matchedPrefix,proto3" json:"matched_prefix,omitempty"`
	// True when the data is self-published by the network operator (geofeeds).
	// Note: v1 does not cryptographically verify geofeeds (RFC 9632 RPKI
	// scheme), so this reflects "self-published", not "verified".
	Authoritative bool `protobuf:"varint,4,opt,name=authoritative,proto3" json:"authoritative,omitempty"`
	// Required attribution / license credit string for this source.
	Attribution string `protobuf:"bytes,5,opt,name=attribution,proto3" json:"attribution,omitempty"`
	// This source's trust level for its own answer.
	Confidence GeoConfidence `protobuf:"varint,6,opt,name=confidence,proto3,enum=ip.GeoConfidence" json:"confidence,omitempty"`
	// Origin Autonomous System number, when the source is BGP-derived (iptoasn).
	// Zero means unknown / not provided by this source.
	Asn uint32 `protobuf:"varint,7,opt,name=asn,proto3" json:"asn,omitempty"`
	// Human-readable network / AS description (e.g. "CLOUDFLARENET").
	Network       string `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSourceResult) Reset() {
	*x = GeoSourceResult{}
	mi := &file_proto_ippb_geo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSourceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSourceResult) ProtoMessage() {}

func (x *GeoSourceResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_geo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSourceResult.ProtoReflect.Descriptor instead.
func (*GeoSourceResult) Descriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{1}
}

func (x *GeoSourceResult) GetSource() GeoSource {
	if x != nil {
		return x.Source
	}
	return GeoSource_GEO_SOURCE_UNKNOWN
}

func (x *GeoSourceResult) GetLocation() *GeoLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GeoSourceResult) GetMatchedPrefix() string {
	if x != nil {
		return x.MatchedPrefix
	}
	return ""
}

func (x *GeoSourceResult) GetAuthoritative() bool {
	if x != nil {
		return x.Authoritative
	}
	return false
}

func (x *GeoSourceResult) GetAttribution() string {
	if x != nil {
		return x.Attribution
	}
	return ""
}

func (x *GeoSourceResult) GetConfidence() GeoConfidence {
	if x != nil {
		return x.Confidence
	}
	return GeoConfidence_GEO_CONFIDENCE_UNKNOWN
}

func (x *GeoSourceResult) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *GeoSourceResult) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

// GeoResponse is the result of a geolocation lookup: one merged best-effort
// location plus every per-source result for transparency.
type GeoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Best-effort merged location: the most granular data available, with
	// coordinates filled from DB-IP and administrative fields preferring an
	// authoritative geofeed when present.
	Best *GeoLocation `protobuf:"bytes,1,opt,name=best,proto3" json:"best,omitempty"`
	// Which source contributed the chosen granularity of `best`.
	BestSource GeoSource `protobuf:"varint,2,opt,name=best_source,json=bestSource,proto3,enum=ip.GeoSource" json:"best_source,omitempty"`
	// Every source that returned a result, in lookup order.
	Sources []*GeoSourceResult `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	// Origin ASN and network name (BGP-derived), lifted from the iptoasn source.
	Asn     uint32 `protobuf:"varint,4,opt,name=asn,proto3" json:"asn,omitempty"`
	Network string `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	// True when the address falls in a known anycast prefix (BGP-derived). When
	// set, `best` coordinates are not a single physical location and `confidence`
	// is forced to LOW.
	Anycast bool `protobuf:"varint,6,opt,name=anycast,proto3" json:"anycast,omitempty"`
	// Overall confidence in `best` (the contributing source's level, lowered to
	// LOW when anycast).
	Confidence    GeoConfidence `protobuf:"varint,7,opt,name=confidence,proto3,enum=ip.GeoConfidence" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoResponse) Reset() {
	*x = GeoResponse{}
	mi := &file_proto_ippb_geo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoResponse) ProtoMessage() {}

func (x *GeoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_geo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoResponse.ProtoReflect.Descriptor instead.
func (*GeoResponse) Descriptor() ([]byte, []int) {
	return file_proto_ippb_geo_proto_rawDescGZIP(), []int{2}
}

func (x *GeoResponse) GetBest() *GeoLocation {
	if x != nil {
		return x.Best
	}
	return nil
}

func (x *GeoResponse) GetBestSource() GeoSource {
	if x != nil {
		return x.BestSource
	}
	return GeoSource_GEO_SOURCE_UNKNOWN
}

func (x *GeoResponse) GetSources() []*GeoSourceResult {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GeoResponse) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *GeoResponse) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GeoResponse) GetAnycast() bool {
	if x != nil {
		return x.Anycast
	}
	return false
}

func (x *GeoResponse) GetConfidence() GeoConfidence {
	if x != nil {
		return x.Confidence
	}
	return GeoConfidence_GEO_CONFIDENCE_UNKNOWN
}

var File_proto_ippb_geo_proto protoreflect.FileDescriptor

const file_proto_ippb_geo_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ippb/geo.proto\x12\x02ip\x1a\x13proto/ippb/ip.proto\x1a\x15proto/ippb/cidr.proto\"\xa6\x02\n" +
	"\vGeoLocation\x12\x1f\n" +
	"\blatitude\x18\x01 \x01(\x01H\x00R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x02 \x01(\x01H\x01R\tlongitude\x88\x01\x01\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x1b\n" +
	"\ttime_zone\x18\a \x01(\tR\btimeZone\x124\n" +
	"\vgranularity\x18\b \x01(\x0e2\x12.ip.GeoGranularityR\vgranularityB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"\xb3\x02\n" +
	"\x0fGeoSourceResult\x12%\n" +
	"\x06source\x18\x01 \x01(\x0e2\r.ip.GeoSourceR\x06source\x12+\n" +
	"\blocation\x18\x02 \x01(\v2\x0f.ip.GeoLocationR\blocation\x12%\n" +
	"\x0ematched_prefix\x18\x03 \x01(\tR\rmatchedPrefix\x12$\n" +
	"\rauthoritative\x18\x04 \x01(\bR\rauthoritative\x12 \n" +
	"\vattribution\x18\x05 \x01(\tR\vattribution\x121\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x0e2\x11.ip.GeoConfidenceR\n" +
	"confidence\x12\x10\n" +
	"\x03asn\x18\a \x01(\rR\x03asn\x12\x18\n" +
	"\anetwork\x18\b \x01(\tR\anetwork\"\x8a\x02\n" +
	"\vGeoResponse\x12#\n" +
	"\x04best\x18\x01 \x01(\v2\x0f.ip.GeoLocationR\x04best\x12.\n" +
	"\vbest_source\x18\x02 \x01(\x0e2\r.ip.GeoSourceR\n" +
	"bestSource\x12-\n" +
	"\asources\x18\x03 \x03(\v2\x13.ip.GeoSourceResultR\asources\x12\x10\n" +
	"\x03asn\x18\x04 \x01(\rR\x03asn\x12\x18\n" +
	"\anetwork\x18\x05 \x01(\tR\anetwork\x12\x18\n" +
	"\aanycast\x18\x06 \x01(\bR\aanycast\x121\n" +
	"\n" +
	"confidence\x18\a \x01(\x0e2\x11.ip.GeoConfidenceR\n" +
	"confidence*\xa4\x01\n" +
	"\tGeoSource\x12\x16\n" +
	"\x12GEO_SOURCE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12GEO_SOURCE_GEOFEED\x10\x01\x12\x18\n" +
	"\x14GEO_SOURCE_DBIP_LITE\x10\x02\x12\x14\n" +
	"\x10GEO_SOURCE_IPMAP\x10\x03\x12\x1f\n" +
	"\x1bGEO_SOURCE_IP2LOCATION_LITE\x10\x04\x12\x16\n" +
	"\x12GEO_SOURCE_IPTOASN\x10\x05*w\n" +
	"\rGeoConfidence\x12\x1a\n" +
	"\x16GEO_CONFIDENCE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12GEO_CONFIDENCE_LOW\x10\x01\x12\x19\n" +
	"\x15GEO_CONFIDENCE_MEDIUM\x10\x02\x12\x17\n" +
	"\x13GEO_CONFIDENCE_HIGH\x10\x03*\xa1\x01\n" +
	"\x0eGeoGranularity\x12\x1b\n" +
	"\x17GEO_GRANULARITY_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17GEO_GRANULARITY_COUNTRY\x10\x01\x12\x1a\n" +
	"\x16GEO_GRANULARITY_REGION\x10\x02\x12\x18\n" +
	"\x14GEO_GRANULARITY_CITY\x10\x03\x12\x1f\n" +
	"\x1bGEO_GRANULARITY_COORDINATES\x10\x042Y\n" +
	"\tGeoLookup\x12#\n" +
	"\bLookupIP\x12\x06.ip.IP\x1a\x0f.ip.GeoResponse\x12'\n" +
	"\n" +
	"LookupCIDR\x12\b.ip.CIDR\x1a\x0f.ip.GeoResponseB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_geo_proto_rawDescOnce sync.Once
	file_proto_ippb_geo_proto_rawDescData []byte
)

func file_proto_ippb_geo_proto_rawDescGZIP() []byte {
	file_proto_ippb_geo_proto_rawDescOnce.Do(func() {
		file_proto_ippb_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_geo_proto_rawDesc), len(file_proto_ippb_geo_proto_rawDesc)))
	})
	return file_proto_ippb_geo_proto_rawDescData
}

var file_proto_ippb_geo_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_ippb_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_ippb_geo_proto_goTypes = []any{
	(GeoSource)(0),          // 0: ip.GeoSource
	(GeoConfidence)(0),      // 1: ip.GeoConfidence
	(GeoGranularity)(0),     // 2: ip.GeoGranularity
	(*GeoLocation)(nil),     // 3: ip.GeoLocation
	(*GeoSourceResult)(nil), // 4: ip.GeoSourceResult
	(*GeoResponse)(nil),     // 5: ip.GeoResponse
	(*IP)(nil),              // 6: ip.IP
	(*CIDR)(nil),            // 7: ip.CIDR
}
var file_proto_ippb_geo_proto_depIdxs = []int32{
	2,  // 0: ip.GeoLocation.granularity:type_name -> ip.GeoGranularity
	0,  // 1: ip.GeoSourceResult.source:type_name -> ip.GeoSource
	3,  // 2: ip.GeoSourceResult.location:type_name -> ip.GeoLocation
	1,  // 3: ip.GeoSourceResult.confidence:type_name -> ip.GeoConfidence
	3,  // 4: ip.GeoResponse.best:type_name -> ip.GeoLocation
	0,  // 5: ip.GeoResponse.best_source:type_name -> ip.GeoSource
	4,  // 6: ip.GeoResponse.sources:type_name -> ip.GeoSourceResult
	1,  // 7: ip.GeoResponse.confidence:type_name -> ip.GeoConfidence
	6,  // 8: ip.GeoLookup.LookupIP:input_type -> ip.IP
	7,  // 9: ip.GeoLookup.LookupCIDR:input_type -> ip.CIDR
	5,  // 10: ip.GeoLookup.LookupIP:output_type -> ip.GeoResponse
	5,  // 11: ip.GeoLookup.LookupCIDR:output_type -> ip.GeoResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ippb_geo_proto_init() }
func file_proto_ippb_geo_proto_init() {
	if File_proto_ippb_geo_proto != nil {
		return
	}
	file_proto_ippb_ip_proto_init()
	file_proto_ippb_cidr_proto_init()
	file_proto_ippb_geo_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_geo_proto_rawDesc), len(file_proto_ippb_geo_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ippb_geo_proto_goTypes,
		DependencyIndexes: file_proto_ippb_geo_proto_depIdxs,
		EnumInfos:         file_proto_ippb_geo_proto_enumTypes,
		MessageInfos:      file_proto_ippb_geo_proto_msgTypes,
	}.Build()
	File_proto_ippb_geo_proto = out.File
	file_proto_ippb_geo_proto_goTypes = nil
	file_proto_ippb_geo_proto_depIdxs = nil
}
