// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/ippb/geo.proto

package ippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoLookup_LookupIP_FullMethodName   = "/ip.GeoLookup/LookupIP"
	GeoLookup_LookupCIDR_FullMethodName = "/ip.GeoLookup/LookupCIDR"
)

// GeoLookupClient is the client API for GeoLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GeoLookup performs best-effort IP geolocation by combining multiple free
// and open data sources. It returns the most granular location available
// (ideally latitude/longitude) and is explicit about gaps and disagreement.
type GeoLookupClient interface {
	// LookupIP geolocates a single IP address.
	LookupIP(ctx context.Context, in *IP, opts ...grpc.CallOption) (*GeoResponse, error)
	// LookupCIDR geolocates a CIDR block (uses the network address).
	LookupCIDR(ctx context.Context, in *CIDR, opts ...grpc.CallOption) (*GeoResponse, error)
}

type geoLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoLookupClient(cc grpc.ClientConnInterface) GeoLookupClient {
	return &geoLookupClient{cc}
}

func (c *geoLookupClient) LookupIP(ctx context.Context, in *IP, opts ...grpc.CallOption) (*GeoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoResponse)
	err := c.cc.Invoke(ctx, GeoLookup_LookupIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoLookupClient) LookupCIDR(ctx context.Context, in *CIDR, opts ...grpc.CallOption) (*GeoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoResponse)
	err := c.cc.Invoke(ctx, GeoLookup_LookupCIDR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoLookupServer is the server API for GeoLookup service.
// All implementations must embed UnimplementedGeoLookupServer
// for forward compatibility.
//
// GeoLookup performs best-effort IP geolocation by combining multiple free
// and open data sources. It returns the most granular location available
// (ideally latitude/longitude) and is explicit about gaps and disagreement.
type GeoLookupServer interface {
	// LookupIP geolocates a single IP address.
	LookupIP(context.Context, *IP) (*GeoResponse, error)
	// LookupCIDR geolocates a CIDR block (uses the network address).
	LookupCIDR(context.Context, *CIDR) (*GeoResponse, error)
	mustEmbedUnimplementedGeoLookupServer()
}

// UnimplementedGeoLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoLookupServer struct{}

func (UnimplementedGeoLookupServer) LookupIP(context.Context, *IP) (*GeoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupIP not implemented")
}
func (UnimplementedGeoLookupServer) LookupCIDR(context.Context, *CIDR) (*GeoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupCIDR not implemented")
}
func (UnimplementedGeoLookupServer) mustEmbedUnimplementedGeoLookupServer() {}
func (UnimplementedGeoLookupServer) testEmbeddedByValue()                   {}

// UnsafeGeoLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoLookupServer will
// result in compilation errors.
type UnsafeGeoLookupServer interface {
	mustEmbedUnimplementedGeoLookupServer()
}

func RegisterGeoLookupServer(s grpc.ServiceRegistrar, srv GeoLookupServer) {
	// If the following call panics, it indicates UnimplementedGeoLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoLookup_ServiceDesc, srv)
}

func _GeoLookup_LookupIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLookupServer).LookupIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLookup_LookupIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLookupServer).LookupIP(ctx, req.(*IP))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoLookup_LookupCIDR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CIDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoLookupServer).LookupCIDR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoLookup_LookupCIDR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoLookupServer).LookupCIDR(ctx, req.(*CIDR))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoLookup_ServiceDesc is the grpc.ServiceDesc for GeoLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ip.GeoLookup",
	HandlerType: (*GeoLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupIP",
			Handler:    _GeoLookup_LookupIP_Handler,
		},
		{
			MethodName: "LookupCIDR",
			Handler:    _GeoLookup_LookupCIDR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ippb/geo.proto",
}
