// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/ip.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IP encodes any IPv4 or IPv6 address as a single 128-bit value split
// into two sint64 halves. IPv4 addresses are stored as IPv4-mapped
// IPv6 (::ffff:0:0/96) on the wire so consumers can treat both
// uniformly. The original client-supplied form is preserved in the
// version oneof for reversible round-tripping and so policy code can
// branch on the intended client family.
type IP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// High 64 bits of the 128-bit address (bytes 0..7).
	// For IPv4 (mapped), the upper 32 bits are zero and the lower 32
	// bits are 0x0000FFFF.
	NetworkPrefix int64 `protobuf:"zigzag64,1,opt,name=network_prefix,json=networkPrefix,proto3" json:"network_prefix,omitempty"`
	// Low 64 bits of the 128-bit address (bytes 8..15).
	// For IPv4 (mapped), the upper 32 bits are zero and the lower 32
	// bits hold the v4 octets.
	InterfaceIdentifier int64 `protobuf:"zigzag64,2,opt,name=interface_identifier,json=interfaceIdentifier,proto3" json:"interface_identifier,omitempty"`
	// Original client-supplied formatting. Wire-level consumers SHOULD
	// ignore this oneof and use the 128-bit value above; humans and
	// round-tripping renderers SHOULD prefer this oneof.
	//
	// Types that are valid to be assigned to Version:
	//
	//	*IP_V4
	//	*IP_V6
	Version       isIP_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IP) Reset() {
	*x = IP{}
	mi := &file_proto_ippb_ip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IP) ProtoMessage() {}

func (x *IP) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_ip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IP.ProtoReflect.Descriptor instead.
func (*IP) Descriptor() ([]byte, []int) {
	return file_proto_ippb_ip_proto_rawDescGZIP(), []int{0}
}

func (x *IP) GetNetworkPrefix() int64 {
	if x != nil {
		return x.NetworkPrefix
	}
	return 0
}

func (x *IP) GetInterfaceIdentifier() int64 {
	if x != nil {
		return x.InterfaceIdentifier
	}
	return 0
}

func (x *IP) GetVersion() isIP_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *IP) GetV4() *IPv4Address {
	if x != nil {
		if x, ok := x.Version.(*IP_V4); ok {
			return x.V4
		}
	}
	return nil
}

func (x *IP) GetV6() *IPv6Address {
	if x != nil {
		if x, ok := x.Version.(*IP_V6); ok {
			return x.V6
		}
	}
	return nil
}

type isIP_Version interface {
	isIP_Version()
}

type IP_V4 struct {
	V4 *IPv4Address `protobuf:"bytes,3,opt,name=v4,proto3,oneof"`
}

type IP_V6 struct {
	V6 *IPv6Address `protobuf:"bytes,4,opt,name=v6,proto3,oneof"`
}

func (*IP_V4) isIP_Version() {}

func (*IP_V6) isIP_Version() {}

var File_proto_ippb_ip_proto protoreflect.FileDescriptor

const file_proto_ippb_ip_proto_rawDesc = "" +
	"\n" +
	"\x13proto/ippb/ip.proto\x12\x02ip\x1a\x15proto/ippb/ipv4.proto\x1a\x15proto/ippb/ipv6.proto\"\xaf\x01\n" +
	"\x02IP\x12%\n" +
	"\x0enetwork_prefix\x18\x01 \x01(\x12R\rnetworkPrefix\x121\n" +
	"\x14interface_identifier\x18\x02 \x01(\x12R\x13interfaceIdentifier\x12!\n" +
	"\x02v4\x18\x03 \x01(\v2\x0f.ip.IPv4AddressH\x00R\x02v4\x12!\n" +
	"\x02v6\x18\x04 \x01(\v2\x0f.ip.IPv6AddressH\x00R\x02v6B\t\n" +
	"\aversionB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_ip_proto_rawDescOnce sync.Once
	file_proto_ippb_ip_proto_rawDescData []byte
)

func file_proto_ippb_ip_proto_rawDescGZIP() []byte {
	file_proto_ippb_ip_proto_rawDescOnce.Do(func() {
		file_proto_ippb_ip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_ip_proto_rawDesc), len(file_proto_ippb_ip_proto_rawDesc)))
	})
	return file_proto_ippb_ip_proto_rawDescData
}

var file_proto_ippb_ip_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ippb_ip_proto_goTypes = []any{
	(*IP)(nil),          // 0: ip.IP
	(*IPv4Address)(nil), // 1: ip.IPv4Address
	(*IPv6Address)(nil), // 2: ip.IPv6Address
}
var file_proto_ippb_ip_proto_depIdxs = []int32{
	1, // 0: ip.IP.v4:type_name -> ip.IPv4Address
	2, // 1: ip.IP.v6:type_name -> ip.IPv6Address
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ippb_ip_proto_init() }
func file_proto_ippb_ip_proto_init() {
	if File_proto_ippb_ip_proto != nil {
		return
	}
	file_proto_ippb_ipv4_proto_init()
	file_proto_ippb_ipv6_proto_init()
	file_proto_ippb_ip_proto_msgTypes[0].OneofWrappers = []any{
		(*IP_V4)(nil),
		(*IP_V6)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_ip_proto_rawDesc), len(file_proto_ippb_ip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ippb_ip_proto_goTypes,
		DependencyIndexes: file_proto_ippb_ip_proto_depIdxs,
		MessageInfos:      file_proto_ippb_ip_proto_msgTypes,
	}.Build()
	File_proto_ippb_ip_proto = out.File
	file_proto_ippb_ip_proto_goTypes = nil
	file_proto_ippb_ip_proto_depIdxs = nil
}
