// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/ipv4.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IPv4Address carries the formatted client-facing representation of a
// single IPv4 address. The on-wire canonical encoding sits on the
// parent IP message (see ip.proto) — this oneof preserves the original
// textual or numeric form the client supplied, so infrastructure can
// distinguish "10.0.0.1" from "0xA000001".
type IPv4Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*IPv4Address_DottedDecimal
	//	*IPv4Address_Num
	//	*IPv4Address_Octets
	//	*IPv4Address_InetAton
	Format        isIPv4Address_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv4Address) Reset() {
	*x = IPv4Address{}
	mi := &file_proto_ippb_ipv4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv4Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv4Address) ProtoMessage() {}

func (x *IPv4Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_ipv4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv4Address.ProtoReflect.Descriptor instead.
func (*IPv4Address) Descriptor() ([]byte, []int) {
	return file_proto_ippb_ipv4_proto_rawDescGZIP(), []int{0}
}

func (x *IPv4Address) GetFormat() isIPv4Address_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *IPv4Address) GetDottedDecimal() string {
	if x != nil {
		if x, ok := x.Format.(*IPv4Address_DottedDecimal); ok {
			return x.DottedDecimal
		}
	}
	return ""
}

func (x *IPv4Address) GetNum() uint32 {
	if x != nil {
		if x, ok := x.Format.(*IPv4Address_Num); ok {
			return x.Num
		}
	}
	return 0
}

func (x *IPv4Address) GetOctets() []byte {
	if x != nil {
		if x, ok := x.Format.(*IPv4Address_Octets); ok {
			return x.Octets
		}
	}
	return nil
}

func (x *IPv4Address) GetInetAton() string {
	if x != nil {
		if x, ok := x.Format.(*IPv4Address_InetAton); ok {
			return x.InetAton
		}
	}
	return ""
}

type isIPv4Address_Format interface {
	isIPv4Address_Format()
}

type IPv4Address_DottedDecimal struct {
	// Dotted-decimal "a.b.c.d", possibly with leading zeros.
	DottedDecimal string `protobuf:"bytes,1,opt,name=dotted_decimal,json=dottedDecimal,proto3,oneof"`
}

type IPv4Address_Num struct {
	// Single 32-bit unsigned integer (host order).
	Num uint32 `protobuf:"varint,2,opt,name=num,proto3,oneof"`
}

type IPv4Address_Octets struct {
	// 4 bytes, network order — what /proc/net etc. produce.
	Octets []byte `protobuf:"bytes,3,opt,name=octets,proto3,oneof"`
}

type IPv4Address_InetAton struct {
	// Mixed/legacy "0xC0.0xA8.1.1" or "1.2.131" inet_aton-style forms,
	// preserved verbatim. Validated by the inet_aton grammar.
	InetAton string `protobuf:"bytes,4,opt,name=inet_aton,json=inetAton,proto3,oneof"`
}

func (*IPv4Address_DottedDecimal) isIPv4Address_Format() {}

func (*IPv4Address_Num) isIPv4Address_Format() {}

func (*IPv4Address_Octets) isIPv4Address_Format() {}

func (*IPv4Address_InetAton) isIPv4Address_Format() {}

var File_proto_ippb_ipv4_proto protoreflect.FileDescriptor

const file_proto_ippb_ipv4_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ippb/ipv4.proto\x12\x02ip\"\x8d\x01\n" +
	"\vIPv4Address\x12'\n" +
	"\x0edotted_decimal\x18\x01 \x01(\tH\x00R\rdottedDecimal\x12\x12\n" +
	"\x03num\x18\x02 \x01(\rH\x00R\x03num\x12\x18\n" +
	"\x06octets\x18\x03 \x01(\fH\x00R\x06octets\x12\x1d\n" +
	"\tinet_aton\x18\x04 \x01(\tH\x00R\binetAtonB\b\n" +
	"\x06formatB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_ipv4_proto_rawDescOnce sync.Once
	file_proto_ippb_ipv4_proto_rawDescData []byte
)

func file_proto_ippb_ipv4_proto_rawDescGZIP() []byte {
	file_proto_ippb_ipv4_proto_rawDescOnce.Do(func() {
		file_proto_ippb_ipv4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_ipv4_proto_rawDesc), len(file_proto_ippb_ipv4_proto_rawDesc)))
	})
	return file_proto_ippb_ipv4_proto_rawDescData
}

var file_proto_ippb_ipv4_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ippb_ipv4_proto_goTypes = []any{
	(*IPv4Address)(nil), // 0: ip.IPv4Address
}
var file_proto_ippb_ipv4_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ippb_ipv4_proto_init() }
func file_proto_ippb_ipv4_proto_init() {
	if File_proto_ippb_ipv4_proto != nil {
		return
	}
	file_proto_ippb_ipv4_proto_msgTypes[0].OneofWrappers = []any{
		(*IPv4Address_DottedDecimal)(nil),
		(*IPv4Address_Num)(nil),
		(*IPv4Address_Octets)(nil),
		(*IPv4Address_InetAton)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_ipv4_proto_rawDesc), len(file_proto_ippb_ipv4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ippb_ipv4_proto_goTypes,
		DependencyIndexes: file_proto_ippb_ipv4_proto_depIdxs,
		MessageInfos:      file_proto_ippb_ipv4_proto_msgTypes,
	}.Build()
	File_proto_ippb_ipv4_proto = out.File
	file_proto_ippb_ipv4_proto_goTypes = nil
	file_proto_ippb_ipv4_proto_depIdxs = nil
}
