// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/ipv6.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IPv6Address carries the formatted client-facing representation of a
// single IPv6 address. The on-wire canonical encoding (16 bytes /
// 128 bits) lives on the parent IP message — this oneof preserves the
// original textual encoding the client supplied.
type IPv6Address struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*IPv6Address_Text
	//	*IPv6Address_Octets
	//	*IPv6Address_ZoneId
	Format        isIPv6Address_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPv6Address) Reset() {
	*x = IPv6Address{}
	mi := &file_proto_ippb_ipv6_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPv6Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPv6Address) ProtoMessage() {}

func (x *IPv6Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_ipv6_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPv6Address.ProtoReflect.Descriptor instead.
func (*IPv6Address) Descriptor() ([]byte, []int) {
	return file_proto_ippb_ipv6_proto_rawDescGZIP(), []int{0}
}

func (x *IPv6Address) GetFormat() isIPv6Address_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *IPv6Address) GetText() string {
	if x != nil {
		if x, ok := x.Format.(*IPv6Address_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *IPv6Address) GetOctets() []byte {
	if x != nil {
		if x, ok := x.Format.(*IPv6Address_Octets); ok {
			return x.Octets
		}
	}
	return nil
}

func (x *IPv6Address) GetZoneId() string {
	if x != nil {
		if x, ok := x.Format.(*IPv6Address_ZoneId); ok {
			return x.ZoneId
		}
	}
	return ""
}

type isIPv6Address_Format interface {
	isIPv6Address_Format()
}

type IPv6Address_Text struct {
	// Full or compressed text form (RFC 4291 / RFC 5952).
	// Examples: "fe80::1", "2001:db8:0:0:0:0:0:1", "::ffff:192.0.2.1".
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type IPv6Address_Octets struct {
	// 16 bytes, network order.
	Octets []byte `protobuf:"bytes,2,opt,name=octets,proto3,oneof"`
}

type IPv6Address_ZoneId struct {
	// Optional zone identifier ("%eth0") for link-local addresses,
	// preserved separately so wire encoding can round-trip it.
	ZoneId string `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3,oneof"`
}

func (*IPv6Address_Text) isIPv6Address_Format() {}

func (*IPv6Address_Octets) isIPv6Address_Format() {}

func (*IPv6Address_ZoneId) isIPv6Address_Format() {}

var File_proto_ippb_ipv6_proto protoreflect.FileDescriptor

const file_proto_ippb_ipv6_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ippb/ipv6.proto\x12\x02ip\"b\n" +
	"\vIPv6Address\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06octets\x18\x02 \x01(\fH\x00R\x06octets\x12\x19\n" +
	"\azone_id\x18\x03 \x01(\tH\x00R\x06zoneIdB\b\n" +
	"\x06formatB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_ipv6_proto_rawDescOnce sync.Once
	file_proto_ippb_ipv6_proto_rawDescData []byte
)

func file_proto_ippb_ipv6_proto_rawDescGZIP() []byte {
	file_proto_ippb_ipv6_proto_rawDescOnce.Do(func() {
		file_proto_ippb_ipv6_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_ipv6_proto_rawDesc), len(file_proto_ippb_ipv6_proto_rawDesc)))
	})
	return file_proto_ippb_ipv6_proto_rawDescData
}

var file_proto_ippb_ipv6_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ippb_ipv6_proto_goTypes = []any{
	(*IPv6Address)(nil), // 0: ip.IPv6Address
}
var file_proto_ippb_ipv6_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ippb_ipv6_proto_init() }
func file_proto_ippb_ipv6_proto_init() {
	if File_proto_ippb_ipv6_proto != nil {
		return
	}
	file_proto_ippb_ipv6_proto_msgTypes[0].OneofWrappers = []any{
		(*IPv6Address_Text)(nil),
		(*IPv6Address_Octets)(nil),
		(*IPv6Address_ZoneId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_ipv6_proto_rawDesc), len(file_proto_ippb_ipv6_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ippb_ipv6_proto_goTypes,
		DependencyIndexes: file_proto_ippb_ipv6_proto_depIdxs,
		MessageInfos:      file_proto_ippb_ipv6_proto_msgTypes,
	}.Build()
	File_proto_ippb_ipv6_proto = out.File
	file_proto_ippb_ipv6_proto_goTypes = nil
	file_proto_ippb_ipv6_proto_depIdxs = nil
}
