// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/local_lookup.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InterfaceClass categorizes a local network interface. The set is
// intentionally small; impl-specific names live in Interface.name.
type InterfaceClass int32

const (
	InterfaceClass_INTERFACE_CLASS_UNKNOWN  InterfaceClass = 0
	InterfaceClass_INTERFACE_CLASS_LOOPBACK InterfaceClass = 1
	// Wired ethernet (eth0, en0 on Darwin, ...).
	InterfaceClass_INTERFACE_CLASS_ETHERNET InterfaceClass = 2
	// Wi-Fi (wlan0, en1 on Darwin, ...).
	InterfaceClass_INTERFACE_CLASS_WIRELESS InterfaceClass = 3
	// Tunnels: utun*, tun*, tap*, wireguard, etc.
	InterfaceClass_INTERFACE_CLASS_TUNNEL InterfaceClass = 4
	// Bridges, VLANs, virtual switches.
	InterfaceClass_INTERFACE_CLASS_VIRTUAL InterfaceClass = 5
)

// Enum value maps for InterfaceClass.
var (
	InterfaceClass_name = map[int32]string{
		0: "INTERFACE_CLASS_UNKNOWN",
		1: "INTERFACE_CLASS_LOOPBACK",
		2: "INTERFACE_CLASS_ETHERNET",
		3: "INTERFACE_CLASS_WIRELESS",
		4: "INTERFACE_CLASS_TUNNEL",
		5: "INTERFACE_CLASS_VIRTUAL",
	}
	InterfaceClass_value = map[string]int32{
		"INTERFACE_CLASS_UNKNOWN":  0,
		"INTERFACE_CLASS_LOOPBACK": 1,
		"INTERFACE_CLASS_ETHERNET": 2,
		"INTERFACE_CLASS_WIRELESS": 3,
		"INTERFACE_CLASS_TUNNEL":   4,
		"INTERFACE_CLASS_VIRTUAL":  5,
	}
)

func (x InterfaceClass) Enum() *InterfaceClass {
	p := new(InterfaceClass)
	*p = x
	return p
}

func (x InterfaceClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_local_lookup_proto_enumTypes[0].Descriptor()
}

func (InterfaceClass) Type() protoreflect.EnumType {
	return &file_proto_ippb_local_lookup_proto_enumTypes[0]
}

func (x InterfaceClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceClass.Descriptor instead.
func (InterfaceClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_local_lookup_proto_rawDescGZIP(), []int{0}
}

// Interface is a single local network interface and its addresses.
type Interface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Class InterfaceClass         `protobuf:"varint,1,opt,name=class,proto3,enum=ip.InterfaceClass" json:"class,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// MAC address, network order. Empty for loopback / virtual.
	HardwareAddress []byte `protobuf:"bytes,3,opt,name=hardware_address,json=hardwareAddress,proto3" json:"hardware_address,omitempty"`
	// All addresses bound to this interface, paired with their subnet.
	Addresses []*CIDR `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// True when the kernel reports the link as up.
	Up            bool `protobuf:"varint,5,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_proto_ippb_local_lookup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_local_lookup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_proto_ippb_local_lookup_proto_rawDescGZIP(), []int{0}
}

func (x *Interface) GetClass() InterfaceClass {
	if x != nil {
		return x.Class
	}
	return InterfaceClass_INTERFACE_CLASS_UNKNOWN
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetHardwareAddress() []byte {
	if x != nil {
		return x.HardwareAddress
	}
	return nil
}

func (x *Interface) GetAddresses() []*CIDR {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Interface) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

// LookupFilter narrows the result set on the server side. Empty filter
// returns everything.
type LookupFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If set, only interfaces whose class matches will be returned.
	Classes []InterfaceClass `protobuf:"varint,1,rep,packed,name=classes,proto3,enum=ip.InterfaceClass" json:"classes,omitempty"`
	// If set, only interfaces whose name matches will be returned.
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// If true, omit loopback, link-local, and private-range addresses.
	OnlyRoutable  bool `protobuf:"varint,3,opt,name=only_routable,json=onlyRoutable,proto3" json:"only_routable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupFilter) Reset() {
	*x = LookupFilter{}
	mi := &file_proto_ippb_local_lookup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupFilter) ProtoMessage() {}

func (x *LookupFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_local_lookup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupFilter.ProtoReflect.Descriptor instead.
func (*LookupFilter) Descriptor() ([]byte, []int) {
	return file_proto_ippb_local_lookup_proto_rawDescGZIP(), []int{1}
}

func (x *LookupFilter) GetClasses() []InterfaceClass {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *LookupFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *LookupFilter) GetOnlyRoutable() bool {
	if x != nil {
		return x.OnlyRoutable
	}
	return false
}

var File_proto_ippb_local_lookup_proto protoreflect.FileDescriptor

const file_proto_ippb_local_lookup_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/ippb/local_lookup.proto\x12\x02ip\x1a\x13proto/ippb/ip.proto\x1a\x15proto/ippb/cidr.proto\"\xac\x01\n" +
	"\tInterface\x12(\n" +
	"\x05class\x18\x01 \x01(\x0e2\x12.ip.InterfaceClassR\x05class\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x10hardware_address\x18\x03 \x01(\fR\x0fhardwareAddress\x12&\n" +
	"\taddresses\x18\x04 \x03(\v2\b.ip.CIDRR\taddresses\x12\x0e\n" +
	"\x02up\x18\x05 \x01(\bR\x02up\"w\n" +
	"\fLookupFilter\x12,\n" +
	"\aclasses\x18\x01 \x03(\x0e2\x12.ip.InterfaceClassR\aclasses\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12#\n" +
	"\ronly_routable\x18\x03 \x01(\bR\fonlyRoutable*\xc0\x01\n" +
	"\x0eInterfaceClass\x12\x1b\n" +
	"\x17INTERFACE_CLASS_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18INTERFACE_CLASS_LOOPBACK\x10\x01\x12\x1c\n" +
	"\x18INTERFACE_CLASS_ETHERNET\x10\x02\x12\x1c\n" +
	"\x18INTERFACE_CLASS_WIRELESS\x10\x03\x12\x1a\n" +
	"\x16INTERFACE_CLASS_TUNNEL\x10\x04\x12\x1b\n" +
	"\x17INTERFACE_CLASS_VIRTUAL\x10\x052i\n" +
	"\vLocalLookup\x123\n" +
	"\x0eListInterfaces\x12\x10.ip.LookupFilter\x1a\r.ip.Interface0\x01\x12%\n" +
	"\aListIPs\x12\x10.ip.LookupFilter\x1a\x06.ip.IP0\x01B1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_local_lookup_proto_rawDescOnce sync.Once
	file_proto_ippb_local_lookup_proto_rawDescData []byte
)

func file_proto_ippb_local_lookup_proto_rawDescGZIP() []byte {
	file_proto_ippb_local_lookup_proto_rawDescOnce.Do(func() {
		file_proto_ippb_local_lookup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_local_lookup_proto_rawDesc), len(file_proto_ippb_local_lookup_proto_rawDesc)))
	})
	return file_proto_ippb_local_lookup_proto_rawDescData
}

var file_proto_ippb_local_lookup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ippb_local_lookup_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ippb_local_lookup_proto_goTypes = []any{
	(InterfaceClass)(0),  // 0: ip.InterfaceClass
	(*Interface)(nil),    // 1: ip.Interface
	(*LookupFilter)(nil), // 2: ip.LookupFilter
	(*CIDR)(nil),         // 3: ip.CIDR
	(*IP)(nil),           // 4: ip.IP
}
var file_proto_ippb_local_lookup_proto_depIdxs = []int32{
	0, // 0: ip.Interface.class:type_name -> ip.InterfaceClass
	3, // 1: ip.Interface.addresses:type_name -> ip.CIDR
	0, // 2: ip.LookupFilter.classes:type_name -> ip.InterfaceClass
	2, // 3: ip.LocalLookup.ListInterfaces:input_type -> ip.LookupFilter
	2, // 4: ip.LocalLookup.ListIPs:input_type -> ip.LookupFilter
	1, // 5: ip.LocalLookup.ListInterfaces:output_type -> ip.Interface
	4, // 6: ip.LocalLookup.ListIPs:output_type -> ip.IP
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ippb_local_lookup_proto_init() }
func file_proto_ippb_local_lookup_proto_init() {
	if File_proto_ippb_local_lookup_proto != nil {
		return
	}
	file_proto_ippb_ip_proto_init()
	file_proto_ippb_cidr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_local_lookup_proto_rawDesc), len(file_proto_ippb_local_lookup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ippb_local_lookup_proto_goTypes,
		DependencyIndexes: file_proto_ippb_local_lookup_proto_depIdxs,
		EnumInfos:         file_proto_ippb_local_lookup_proto_enumTypes,
		MessageInfos:      file_proto_ippb_local_lookup_proto_msgTypes,
	}.Build()
	File_proto_ippb_local_lookup_proto = out.File
	file_proto_ippb_local_lookup_proto_goTypes = nil
	file_proto_ippb_local_lookup_proto_depIdxs = nil
}
