// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/ippb/local_lookup.proto

package ippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalLookup_ListInterfaces_FullMethodName = "/ip.LocalLookup/ListInterfaces"
	LocalLookup_ListIPs_FullMethodName        = "/ip.LocalLookup/ListIPs"
)

// LocalLookupClient is the client API for LocalLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalLookup serves IP information from the host kernel
// (procfs on Linux, route/getifaddrs/sysctl on Darwin).
// Implementations MUST NOT cache results across calls — each request
// reads live state.
type LocalLookupClient interface {
	// ListInterfaces streams every interface + its bound addresses.
	ListInterfaces(ctx context.Context, in *LookupFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Interface], error)
	// ListIPs streams every locally-bound IP address (across all
	// interfaces). Convenience wrapper around ListInterfaces.
	ListIPs(ctx context.Context, in *LookupFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IP], error)
}

type localLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalLookupClient(cc grpc.ClientConnInterface) LocalLookupClient {
	return &localLookupClient{cc}
}

func (c *localLookupClient) ListInterfaces(ctx context.Context, in *LookupFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Interface], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalLookup_ServiceDesc.Streams[0], LocalLookup_ListInterfaces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LookupFilter, Interface]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLookup_ListInterfacesClient = grpc.ServerStreamingClient[Interface]

func (c *localLookupClient) ListIPs(ctx context.Context, in *LookupFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IP], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalLookup_ServiceDesc.Streams[1], LocalLookup_ListIPs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LookupFilter, IP]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLookup_ListIPsClient = grpc.ServerStreamingClient[IP]

// LocalLookupServer is the server API for LocalLookup service.
// All implementations must embed UnimplementedLocalLookupServer
// for forward compatibility.
//
// LocalLookup serves IP information from the host kernel
// (procfs on Linux, route/getifaddrs/sysctl on Darwin).
// Implementations MUST NOT cache results across calls — each request
// reads live state.
type LocalLookupServer interface {
	// ListInterfaces streams every interface + its bound addresses.
	ListInterfaces(*LookupFilter, grpc.ServerStreamingServer[Interface]) error
	// ListIPs streams every locally-bound IP address (across all
	// interfaces). Convenience wrapper around ListInterfaces.
	ListIPs(*LookupFilter, grpc.ServerStreamingServer[IP]) error
	mustEmbedUnimplementedLocalLookupServer()
}

// UnimplementedLocalLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalLookupServer struct{}

func (UnimplementedLocalLookupServer) ListInterfaces(*LookupFilter, grpc.ServerStreamingServer[Interface]) error {
	return status.Errorf(codes.Unimplemented, "method ListInterfaces not implemented")
}
func (UnimplementedLocalLookupServer) ListIPs(*LookupFilter, grpc.ServerStreamingServer[IP]) error {
	return status.Errorf(codes.Unimplemented, "method ListIPs not implemented")
}
func (UnimplementedLocalLookupServer) mustEmbedUnimplementedLocalLookupServer() {}
func (UnimplementedLocalLookupServer) testEmbeddedByValue()                     {}

// UnsafeLocalLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalLookupServer will
// result in compilation errors.
type UnsafeLocalLookupServer interface {
	mustEmbedUnimplementedLocalLookupServer()
}

func RegisterLocalLookupServer(s grpc.ServiceRegistrar, srv LocalLookupServer) {
	// If the following call pancis, it indicates UnimplementedLocalLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalLookup_ServiceDesc, srv)
}

func _LocalLookup_ListInterfaces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalLookupServer).ListInterfaces(m, &grpc.GenericServerStream[LookupFilter, Interface]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLookup_ListInterfacesServer = grpc.ServerStreamingServer[Interface]

func _LocalLookup_ListIPs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalLookupServer).ListIPs(m, &grpc.GenericServerStream[LookupFilter, IP]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalLookup_ListIPsServer = grpc.ServerStreamingServer[IP]

// LocalLookup_ServiceDesc is the grpc.ServiceDesc for LocalLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ip.LocalLookup",
	HandlerType: (*LocalLookupServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListInterfaces",
			Handler:       _LocalLookup_ListInterfaces_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListIPs",
			Handler:       _LocalLookup_ListIPs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ippb/local_lookup.proto",
}
