// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/ippb/rdap.proto

package ippb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RDAPLookup_LookupIP_FullMethodName   = "/ip.RDAPLookup/LookupIP"
	RDAPLookup_LookupCIDR_FullMethodName = "/ip.RDAPLookup/LookupCIDR"
)

// RDAPLookupClient is the client API for RDAPLookup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RDAPLookup performs RDAP registration lookups for IP addresses and
// CIDR blocks. It uses the IANA bootstrap registry (RFC 7484) to
// route each query to the correct Regional Internet Registry.
type RDAPLookupClient interface {
	// LookupIP queries the RDAP registry for a single IP address.
	LookupIP(ctx context.Context, in *IP, opts ...grpc.CallOption) (*RDAPResponse, error)
	// LookupCIDR queries the RDAP registry for a CIDR block.
	// The full prefix (e.g. "10.0.0.0/8") is forwarded to the RIR so
	// the response covers the exact block, not just the containing one.
	LookupCIDR(ctx context.Context, in *CIDR, opts ...grpc.CallOption) (*RDAPResponse, error)
}

type rDAPLookupClient struct {
	cc grpc.ClientConnInterface
}

func NewRDAPLookupClient(cc grpc.ClientConnInterface) RDAPLookupClient {
	return &rDAPLookupClient{cc}
}

func (c *rDAPLookupClient) LookupIP(ctx context.Context, in *IP, opts ...grpc.CallOption) (*RDAPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RDAPResponse)
	err := c.cc.Invoke(ctx, RDAPLookup_LookupIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rDAPLookupClient) LookupCIDR(ctx context.Context, in *CIDR, opts ...grpc.CallOption) (*RDAPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RDAPResponse)
	err := c.cc.Invoke(ctx, RDAPLookup_LookupCIDR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RDAPLookupServer is the server API for RDAPLookup service.
// All implementations must embed UnimplementedRDAPLookupServer
// for forward compatibility.
//
// RDAPLookup performs RDAP registration lookups for IP addresses and
// CIDR blocks. It uses the IANA bootstrap registry (RFC 7484) to
// route each query to the correct Regional Internet Registry.
type RDAPLookupServer interface {
	// LookupIP queries the RDAP registry for a single IP address.
	LookupIP(context.Context, *IP) (*RDAPResponse, error)
	// LookupCIDR queries the RDAP registry for a CIDR block.
	// The full prefix (e.g. "10.0.0.0/8") is forwarded to the RIR so
	// the response covers the exact block, not just the containing one.
	LookupCIDR(context.Context, *CIDR) (*RDAPResponse, error)
	mustEmbedUnimplementedRDAPLookupServer()
}

// UnimplementedRDAPLookupServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRDAPLookupServer struct{}

func (UnimplementedRDAPLookupServer) LookupIP(context.Context, *IP) (*RDAPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupIP not implemented")
}
func (UnimplementedRDAPLookupServer) LookupCIDR(context.Context, *CIDR) (*RDAPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupCIDR not implemented")
}
func (UnimplementedRDAPLookupServer) mustEmbedUnimplementedRDAPLookupServer() {}
func (UnimplementedRDAPLookupServer) testEmbeddedByValue()                    {}

// UnsafeRDAPLookupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RDAPLookupServer will
// result in compilation errors.
type UnsafeRDAPLookupServer interface {
	mustEmbedUnimplementedRDAPLookupServer()
}

func RegisterRDAPLookupServer(s grpc.ServiceRegistrar, srv RDAPLookupServer) {
	// If the following call panics, it indicates UnimplementedRDAPLookupServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RDAPLookup_ServiceDesc, srv)
}

func _RDAPLookup_LookupIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RDAPLookupServer).LookupIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RDAPLookup_LookupIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RDAPLookupServer).LookupIP(ctx, req.(*IP))
	}
	return interceptor(ctx, in, info, handler)
}

func _RDAPLookup_LookupCIDR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CIDR)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RDAPLookupServer).LookupCIDR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RDAPLookup_LookupCIDR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RDAPLookupServer).LookupCIDR(ctx, req.(*CIDR))
	}
	return interceptor(ctx, in, info, handler)
}

// RDAPLookup_ServiceDesc is the grpc.ServiceDesc for RDAPLookup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RDAPLookup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ip.RDAPLookup",
	HandlerType: (*RDAPLookupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupIP",
			Handler:    _RDAPLookup_LookupIP_Handler,
		},
		{
			MethodName: "LookupCIDR",
			Handler:    _RDAPLookup_LookupCIDR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ippb/rdap.proto",
}
