// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/rdap.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RDAPIPVersion is the address family reported by an RDAP server.
// RFC 7483 defines exactly two values; UNKNOWN covers unrecognised strings.
type RDAPIPVersion int32

const (
	RDAPIPVersion_RDAP_IP_VERSION_UNKNOWN RDAPIPVersion = 0
	RDAPIPVersion_RDAP_IP_VERSION_V4      RDAPIPVersion = 1
	RDAPIPVersion_RDAP_IP_VERSION_V6      RDAPIPVersion = 2
)

// Enum value maps for RDAPIPVersion.
var (
	RDAPIPVersion_name = map[int32]string{
		0: "RDAP_IP_VERSION_UNKNOWN",
		1: "RDAP_IP_VERSION_V4",
		2: "RDAP_IP_VERSION_V6",
	}
	RDAPIPVersion_value = map[string]int32{
		"RDAP_IP_VERSION_UNKNOWN": 0,
		"RDAP_IP_VERSION_V4":      1,
		"RDAP_IP_VERSION_V6":      2,
	}
)

func (x RDAPIPVersion) Enum() *RDAPIPVersion {
	p := new(RDAPIPVersion)
	*p = x
	return p
}

func (x RDAPIPVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RDAPIPVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_rdap_proto_enumTypes[0].Descriptor()
}

func (RDAPIPVersion) Type() protoreflect.EnumType {
	return &file_proto_ippb_rdap_proto_enumTypes[0]
}

func (x RDAPIPVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RDAPIPVersion.Descriptor instead.
func (RDAPIPVersion) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{0}
}

// RDAPRole enumerates the entity roles defined by RFC 7483 §10.2.4
// and the IANA RDAP JSON Values registry.
type RDAPRole int32

const (
	RDAPRole_RDAP_ROLE_UNKNOWN                   RDAPRole = 0
	RDAPRole_RDAP_ROLE_REGISTRANT                RDAPRole = 1
	RDAPRole_RDAP_ROLE_TECHNICAL                 RDAPRole = 2
	RDAPRole_RDAP_ROLE_ADMINISTRATIVE            RDAPRole = 3
	RDAPRole_RDAP_ROLE_ABUSE                     RDAPRole = 4
	RDAPRole_RDAP_ROLE_NOC                       RDAPRole = 5
	RDAPRole_RDAP_ROLE_BILLING                   RDAPRole = 6
	RDAPRole_RDAP_ROLE_REGISTRAR                 RDAPRole = 7
	RDAPRole_RDAP_ROLE_RESELLER                  RDAPRole = 8
	RDAPRole_RDAP_ROLE_SPONSOR                   RDAPRole = 9
	RDAPRole_RDAP_ROLE_PROXY                     RDAPRole = 10
	RDAPRole_RDAP_ROLE_NOTIFICATIONS             RDAPRole = 11
	RDAPRole_RDAP_ROLE_NOC_DEFAULT_ABUSE_CONTACT RDAPRole = 12
)

// Enum value maps for RDAPRole.
var (
	RDAPRole_name = map[int32]string{
		0:  "RDAP_ROLE_UNKNOWN",
		1:  "RDAP_ROLE_REGISTRANT",
		2:  "RDAP_ROLE_TECHNICAL",
		3:  "RDAP_ROLE_ADMINISTRATIVE",
		4:  "RDAP_ROLE_ABUSE",
		5:  "RDAP_ROLE_NOC",
		6:  "RDAP_ROLE_BILLING",
		7:  "RDAP_ROLE_REGISTRAR",
		8:  "RDAP_ROLE_RESELLER",
		9:  "RDAP_ROLE_SPONSOR",
		10: "RDAP_ROLE_PROXY",
		11: "RDAP_ROLE_NOTIFICATIONS",
		12: "RDAP_ROLE_NOC_DEFAULT_ABUSE_CONTACT",
	}
	RDAPRole_value = map[string]int32{
		"RDAP_ROLE_UNKNOWN":                   0,
		"RDAP_ROLE_REGISTRANT":                1,
		"RDAP_ROLE_TECHNICAL":                 2,
		"RDAP_ROLE_ADMINISTRATIVE":            3,
		"RDAP_ROLE_ABUSE":                     4,
		"RDAP_ROLE_NOC":                       5,
		"RDAP_ROLE_BILLING":                   6,
		"RDAP_ROLE_REGISTRAR":                 7,
		"RDAP_ROLE_RESELLER":                  8,
		"RDAP_ROLE_SPONSOR":                   9,
		"RDAP_ROLE_PROXY":                     10,
		"RDAP_ROLE_NOTIFICATIONS":             11,
		"RDAP_ROLE_NOC_DEFAULT_ABUSE_CONTACT": 12,
	}
)

func (x RDAPRole) Enum() *RDAPRole {
	p := new(RDAPRole)
	*p = x
	return p
}

func (x RDAPRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RDAPRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_rdap_proto_enumTypes[1].Descriptor()
}

func (RDAPRole) Type() protoreflect.EnumType {
	return &file_proto_ippb_rdap_proto_enumTypes[1]
}

func (x RDAPRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RDAPRole.Descriptor instead.
func (RDAPRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{1}
}

// RDAPEventAction enumerates the eventAction values defined by
// RFC 7483 §10.2.3 and the IANA RDAP JSON Values registry.
type RDAPEventAction int32

const (
	RDAPEventAction_RDAP_EVENT_ACTION_UNKNOWN                      RDAPEventAction = 0
	RDAPEventAction_RDAP_EVENT_ACTION_REGISTRATION                 RDAPEventAction = 1
	RDAPEventAction_RDAP_EVENT_ACTION_REREGISTRATION               RDAPEventAction = 2
	RDAPEventAction_RDAP_EVENT_ACTION_LAST_CHANGED                 RDAPEventAction = 3
	RDAPEventAction_RDAP_EVENT_ACTION_EXPIRATION                   RDAPEventAction = 4
	RDAPEventAction_RDAP_EVENT_ACTION_DELETION                     RDAPEventAction = 5
	RDAPEventAction_RDAP_EVENT_ACTION_REINSTANTIATION              RDAPEventAction = 6
	RDAPEventAction_RDAP_EVENT_ACTION_TRANSFER                     RDAPEventAction = 7
	RDAPEventAction_RDAP_EVENT_ACTION_LOCKED                       RDAPEventAction = 8
	RDAPEventAction_RDAP_EVENT_ACTION_UNLOCKED                     RDAPEventAction = 9
	RDAPEventAction_RDAP_EVENT_ACTION_LAST_UPDATE_OF_RDAP_DATABASE RDAPEventAction = 10
	RDAPEventAction_RDAP_EVENT_ACTION_REGISTRAR_EXPIRATION         RDAPEventAction = 11
	RDAPEventAction_RDAP_EVENT_ACTION_ENUM_VALIDATION_EXPIRATION   RDAPEventAction = 12
)

// Enum value maps for RDAPEventAction.
var (
	RDAPEventAction_name = map[int32]string{
		0:  "RDAP_EVENT_ACTION_UNKNOWN",
		1:  "RDAP_EVENT_ACTION_REGISTRATION",
		2:  "RDAP_EVENT_ACTION_REREGISTRATION",
		3:  "RDAP_EVENT_ACTION_LAST_CHANGED",
		4:  "RDAP_EVENT_ACTION_EXPIRATION",
		5:  "RDAP_EVENT_ACTION_DELETION",
		6:  "RDAP_EVENT_ACTION_REINSTANTIATION",
		7:  "RDAP_EVENT_ACTION_TRANSFER",
		8:  "RDAP_EVENT_ACTION_LOCKED",
		9:  "RDAP_EVENT_ACTION_UNLOCKED",
		10: "RDAP_EVENT_ACTION_LAST_UPDATE_OF_RDAP_DATABASE",
		11: "RDAP_EVENT_ACTION_REGISTRAR_EXPIRATION",
		12: "RDAP_EVENT_ACTION_ENUM_VALIDATION_EXPIRATION",
	}
	RDAPEventAction_value = map[string]int32{
		"RDAP_EVENT_ACTION_UNKNOWN":                      0,
		"RDAP_EVENT_ACTION_REGISTRATION":                 1,
		"RDAP_EVENT_ACTION_REREGISTRATION":               2,
		"RDAP_EVENT_ACTION_LAST_CHANGED":                 3,
		"RDAP_EVENT_ACTION_EXPIRATION":                   4,
		"RDAP_EVENT_ACTION_DELETION":                     5,
		"RDAP_EVENT_ACTION_REINSTANTIATION":              6,
		"RDAP_EVENT_ACTION_TRANSFER":                     7,
		"RDAP_EVENT_ACTION_LOCKED":                       8,
		"RDAP_EVENT_ACTION_UNLOCKED":                     9,
		"RDAP_EVENT_ACTION_LAST_UPDATE_OF_RDAP_DATABASE": 10,
		"RDAP_EVENT_ACTION_REGISTRAR_EXPIRATION":         11,
		"RDAP_EVENT_ACTION_ENUM_VALIDATION_EXPIRATION":   12,
	}
)

func (x RDAPEventAction) Enum() *RDAPEventAction {
	p := new(RDAPEventAction)
	*p = x
	return p
}

func (x RDAPEventAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RDAPEventAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_rdap_proto_enumTypes[2].Descriptor()
}

func (RDAPEventAction) Type() protoreflect.EnumType {
	return &file_proto_ippb_rdap_proto_enumTypes[2]
}

func (x RDAPEventAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RDAPEventAction.Descriptor instead.
func (RDAPEventAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{2}
}

// RDAPStatus enumerates the status values defined by RFC 7483 §10.2.1
// and the IANA RDAP JSON Values registry.
type RDAPStatus int32

const (
	RDAPStatus_RDAP_STATUS_UNKNOWN             RDAPStatus = 0
	RDAPStatus_RDAP_STATUS_ACTIVE              RDAPStatus = 1
	RDAPStatus_RDAP_STATUS_INACTIVE            RDAPStatus = 2
	RDAPStatus_RDAP_STATUS_VALIDATED           RDAPStatus = 3
	RDAPStatus_RDAP_STATUS_RENEW_PROHIBITED    RDAPStatus = 4
	RDAPStatus_RDAP_STATUS_UPDATE_PROHIBITED   RDAPStatus = 5
	RDAPStatus_RDAP_STATUS_TRANSFER_PROHIBITED RDAPStatus = 6
	RDAPStatus_RDAP_STATUS_DELETE_PROHIBITED   RDAPStatus = 7
	RDAPStatus_RDAP_STATUS_PROXY               RDAPStatus = 8
	RDAPStatus_RDAP_STATUS_PRIVATE             RDAPStatus = 9
	RDAPStatus_RDAP_STATUS_REMOVED             RDAPStatus = 10
	RDAPStatus_RDAP_STATUS_OBSCURED            RDAPStatus = 11
	RDAPStatus_RDAP_STATUS_ASSOCIATED          RDAPStatus = 12
	RDAPStatus_RDAP_STATUS_LOCKED              RDAPStatus = 13
	RDAPStatus_RDAP_STATUS_PENDING_CREATE      RDAPStatus = 14
	RDAPStatus_RDAP_STATUS_PENDING_RENEW       RDAPStatus = 15
	RDAPStatus_RDAP_STATUS_PENDING_TRANSFER    RDAPStatus = 16
	RDAPStatus_RDAP_STATUS_PENDING_UPDATE      RDAPStatus = 17
	RDAPStatus_RDAP_STATUS_PENDING_DELETE      RDAPStatus = 18
)

// Enum value maps for RDAPStatus.
var (
	RDAPStatus_name = map[int32]string{
		0:  "RDAP_STATUS_UNKNOWN",
		1:  "RDAP_STATUS_ACTIVE",
		2:  "RDAP_STATUS_INACTIVE",
		3:  "RDAP_STATUS_VALIDATED",
		4:  "RDAP_STATUS_RENEW_PROHIBITED",
		5:  "RDAP_STATUS_UPDATE_PROHIBITED",
		6:  "RDAP_STATUS_TRANSFER_PROHIBITED",
		7:  "RDAP_STATUS_DELETE_PROHIBITED",
		8:  "RDAP_STATUS_PROXY",
		9:  "RDAP_STATUS_PRIVATE",
		10: "RDAP_STATUS_REMOVED",
		11: "RDAP_STATUS_OBSCURED",
		12: "RDAP_STATUS_ASSOCIATED",
		13: "RDAP_STATUS_LOCKED",
		14: "RDAP_STATUS_PENDING_CREATE",
		15: "RDAP_STATUS_PENDING_RENEW",
		16: "RDAP_STATUS_PENDING_TRANSFER",
		17: "RDAP_STATUS_PENDING_UPDATE",
		18: "RDAP_STATUS_PENDING_DELETE",
	}
	RDAPStatus_value = map[string]int32{
		"RDAP_STATUS_UNKNOWN":             0,
		"RDAP_STATUS_ACTIVE":              1,
		"RDAP_STATUS_INACTIVE":            2,
		"RDAP_STATUS_VALIDATED":           3,
		"RDAP_STATUS_RENEW_PROHIBITED":    4,
		"RDAP_STATUS_UPDATE_PROHIBITED":   5,
		"RDAP_STATUS_TRANSFER_PROHIBITED": 6,
		"RDAP_STATUS_DELETE_PROHIBITED":   7,
		"RDAP_STATUS_PROXY":               8,
		"RDAP_STATUS_PRIVATE":             9,
		"RDAP_STATUS_REMOVED":             10,
		"RDAP_STATUS_OBSCURED":            11,
		"RDAP_STATUS_ASSOCIATED":          12,
		"RDAP_STATUS_LOCKED":              13,
		"RDAP_STATUS_PENDING_CREATE":      14,
		"RDAP_STATUS_PENDING_RENEW":       15,
		"RDAP_STATUS_PENDING_TRANSFER":    16,
		"RDAP_STATUS_PENDING_UPDATE":      17,
		"RDAP_STATUS_PENDING_DELETE":      18,
	}
)

func (x RDAPStatus) Enum() *RDAPStatus {
	p := new(RDAPStatus)
	*p = x
	return p
}

func (x RDAPStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RDAPStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ippb_rdap_proto_enumTypes[3].Descriptor()
}

func (RDAPStatus) Type() protoreflect.EnumType {
	return &file_proto_ippb_rdap_proto_enumTypes[3]
}

func (x RDAPStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RDAPStatus.Descriptor instead.
func (RDAPStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{3}
}

// RDAPEntity is a contact or organization from an RDAP response,
// extracted from the vCard embedded in the entity object.
type RDAPEntity struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Full name from vCard FN property.
	Fn            string     `protobuf:"bytes,2,opt,name=fn,proto3" json:"fn,omitempty"`
	Roles         []RDAPRole `protobuf:"varint,3,rep,packed,name=roles,proto3,enum=ip.RDAPRole" json:"roles,omitempty"`
	Emails        []string   `protobuf:"bytes,4,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPEntity) Reset() {
	*x = RDAPEntity{}
	mi := &file_proto_ippb_rdap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPEntity) ProtoMessage() {}

func (x *RDAPEntity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_rdap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPEntity.ProtoReflect.Descriptor instead.
func (*RDAPEntity) Descriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{0}
}

func (x *RDAPEntity) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *RDAPEntity) GetFn() string {
	if x != nil {
		return x.Fn
	}
	return ""
}

func (x *RDAPEntity) GetRoles() []RDAPRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RDAPEntity) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

// RDAPEvent corresponds to an RDAP eventAction / eventDate pair.
type RDAPEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Action RDAPEventAction        `protobuf:"varint,1,opt,name=action,proto3,enum=ip.RDAPEventAction" json:"action,omitempty"`
	// ISO 8601 date string as returned by the RIR.
	Date          string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPEvent) Reset() {
	*x = RDAPEvent{}
	mi := &file_proto_ippb_rdap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPEvent) ProtoMessage() {}

func (x *RDAPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_rdap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPEvent.ProtoReflect.Descriptor instead.
func (*RDAPEvent) Descriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{1}
}

func (x *RDAPEvent) GetAction() RDAPEventAction {
	if x != nil {
		return x.Action
	}
	return RDAPEventAction_RDAP_EVENT_ACTION_UNKNOWN
}

func (x *RDAPEvent) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// RDAPNetwork is the core ip network object returned by an RDAP registry.
type RDAPNetwork struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RIR-assigned handle (e.g. "NET-8-8-8-0-1" from ARIN).
	Handle string `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Human-readable name of the network block.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Allocation type (e.g. "DIRECT ALLOCATION"). Left as string because
	// RIRs use values beyond the IANA-registered set.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// First address of the block, as returned by the RIR (text form).
	StartAddress string `protobuf:"bytes,4,opt,name=start_address,json=startAddress,proto3" json:"start_address,omitempty"`
	// Last address of the block.
	EndAddress string        `protobuf:"bytes,5,opt,name=end_address,json=endAddress,proto3" json:"end_address,omitempty"`
	IpVersion  RDAPIPVersion `protobuf:"varint,6,opt,name=ip_version,json=ipVersion,proto3,enum=ip.RDAPIPVersion" json:"ip_version,omitempty"`
	// ISO 3166-1 alpha-2 country code.
	Country  string        `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Status   []RDAPStatus  `protobuf:"varint,8,rep,packed,name=status,proto3,enum=ip.RDAPStatus" json:"status,omitempty"`
	Entities []*RDAPEntity `protobuf:"bytes,9,rep,name=entities,proto3" json:"entities,omitempty"`
	Events   []*RDAPEvent  `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	// Self / alternate link hrefs from the RDAP links array.
	Links []string `protobuf:"bytes,11,rep,name=links,proto3" json:"links,omitempty"`
	// Base URL of the RDAP server that was queried.
	RdapServer    string `protobuf:"bytes,12,opt,name=rdap_server,json=rdapServer,proto3" json:"rdap_server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPNetwork) Reset() {
	*x = RDAPNetwork{}
	mi := &file_proto_ippb_rdap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPNetwork) ProtoMessage() {}

func (x *RDAPNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_rdap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPNetwork.ProtoReflect.Descriptor instead.
func (*RDAPNetwork) Descriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{2}
}

func (x *RDAPNetwork) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *RDAPNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RDAPNetwork) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RDAPNetwork) GetStartAddress() string {
	if x != nil {
		return x.StartAddress
	}
	return ""
}

func (x *RDAPNetwork) GetEndAddress() string {
	if x != nil {
		return x.EndAddress
	}
	return ""
}

func (x *RDAPNetwork) GetIpVersion() RDAPIPVersion {
	if x != nil {
		return x.IpVersion
	}
	return RDAPIPVersion_RDAP_IP_VERSION_UNKNOWN
}

func (x *RDAPNetwork) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RDAPNetwork) GetStatus() []RDAPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RDAPNetwork) GetEntities() []*RDAPEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *RDAPNetwork) GetEvents() []*RDAPEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *RDAPNetwork) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *RDAPNetwork) GetRdapServer() string {
	if x != nil {
		return x.RdapServer
	}
	return ""
}

// RDAPResponse wraps the parsed ip network registration record.
type RDAPResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Network *RDAPNetwork           `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	// Full RDAP JSON response body, preserved for callers that need
	// fields not modelled in RDAPNetwork.
	RawJson       string `protobuf:"bytes,2,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RDAPResponse) Reset() {
	*x = RDAPResponse{}
	mi := &file_proto_ippb_rdap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RDAPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RDAPResponse) ProtoMessage() {}

func (x *RDAPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_rdap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RDAPResponse.ProtoReflect.Descriptor instead.
func (*RDAPResponse) Descriptor() ([]byte, []int) {
	return file_proto_ippb_rdap_proto_rawDescGZIP(), []int{3}
}

func (x *RDAPResponse) GetNetwork() *RDAPNetwork {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *RDAPResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

var File_proto_ippb_rdap_proto protoreflect.FileDescriptor

const file_proto_ippb_rdap_proto_rawDesc = "" +
	"\n" +
	"\x15proto/ippb/rdap.proto\x12\x02ip\x1a\x13proto/ippb/ip.proto\x1a\x15proto/ippb/cidr.proto\"p\n" +
	"\n" +
	"RDAPEntity\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x0e\n" +
	"\x02fn\x18\x02 \x01(\tR\x02fn\x12\"\n" +
	"\x05roles\x18\x03 \x03(\x0e2\f.ip.RDAPRoleR\x05roles\x12\x16\n" +
	"\x06emails\x18\x04 \x03(\tR\x06emails\"L\n" +
	"\tRDAPEvent\x12+\n" +
	"\x06action\x18\x01 \x01(\x0e2\x13.ip.RDAPEventActionR\x06action\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"\x91\x03\n" +
	"\vRDAPNetwork\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12#\n" +
	"\rstart_address\x18\x04 \x01(\tR\fstartAddress\x12\x1f\n" +
	"\vend_address\x18\x05 \x01(\tR\n" +
	"endAddress\x120\n" +
	"\n" +
	"ip_version\x18\x06 \x01(\x0e2\x11.ip.RDAPIPVersionR\tipVersion\x12\x18\n" +
	"\acountry\x18\a \x01(\tR\acountry\x12&\n" +
	"\x06status\x18\b \x03(\x0e2\x0e.ip.RDAPStatusR\x06status\x12*\n" +
	"\bentities\x18\t \x03(\v2\x0e.ip.RDAPEntityR\bentities\x12%\n" +
	"\x06events\x18\n" +
	" \x03(\v2\r.ip.RDAPEventR\x06events\x12\x14\n" +
	"\x05links\x18\v \x03(\tR\x05links\x12\x1f\n" +
	"\vrdap_server\x18\f \x01(\tR\n" +
	"rdapServer\"T\n" +
	"\fRDAPResponse\x12)\n" +
	"\anetwork\x18\x01 \x01(\v2\x0f.ip.RDAPNetworkR\anetwork\x12\x19\n" +
	"\braw_json\x18\x02 \x01(\tR\arawJson*\\\n" +
	"\rRDAPIPVersion\x12\x1b\n" +
	"\x17RDAP_IP_VERSION_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12RDAP_IP_VERSION_V4\x10\x01\x12\x16\n" +
	"\x12RDAP_IP_VERSION_V6\x10\x02*\xd4\x02\n" +
	"\bRDAPRole\x12\x15\n" +
	"\x11RDAP_ROLE_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14RDAP_ROLE_REGISTRANT\x10\x01\x12\x17\n" +
	"\x13RDAP_ROLE_TECHNICAL\x10\x02\x12\x1c\n" +
	"\x18RDAP_ROLE_ADMINISTRATIVE\x10\x03\x12\x13\n" +
	"\x0fRDAP_ROLE_ABUSE\x10\x04\x12\x11\n" +
	"\rRDAP_ROLE_NOC\x10\x05\x12\x15\n" +
	"\x11RDAP_ROLE_BILLING\x10\x06\x12\x17\n" +
	"\x13RDAP_ROLE_REGISTRAR\x10\a\x12\x16\n" +
	"\x12RDAP_ROLE_RESELLER\x10\b\x12\x15\n" +
	"\x11RDAP_ROLE_SPONSOR\x10\t\x12\x13\n" +
	"\x0fRDAP_ROLE_PROXY\x10\n" +
	"\x12\x1b\n" +
	"\x17RDAP_ROLE_NOTIFICATIONS\x10\v\x12'\n" +
	"#RDAP_ROLE_NOC_DEFAULT_ABUSE_CONTACT\x10\f*\xf7\x03\n" +
	"\x0fRDAPEventAction\x12\x1d\n" +
	"\x19RDAP_EVENT_ACTION_UNKNOWN\x10\x00\x12\"\n" +
	"\x1eRDAP_EVENT_ACTION_REGISTRATION\x10\x01\x12$\n" +
	" RDAP_EVENT_ACTION_REREGISTRATION\x10\x02\x12\"\n" +
	"\x1eRDAP_EVENT_ACTION_LAST_CHANGED\x10\x03\x12 \n" +
	"\x1cRDAP_EVENT_ACTION_EXPIRATION\x10\x04\x12\x1e\n" +
	"\x1aRDAP_EVENT_ACTION_DELETION\x10\x05\x12%\n" +
	"!RDAP_EVENT_ACTION_REINSTANTIATION\x10\x06\x12\x1e\n" +
	"\x1aRDAP_EVENT_ACTION_TRANSFER\x10\a\x12\x1c\n" +
	"\x18RDAP_EVENT_ACTION_LOCKED\x10\b\x12\x1e\n" +
	"\x1aRDAP_EVENT_ACTION_UNLOCKED\x10\t\x122\n" +
	".RDAP_EVENT_ACTION_LAST_UPDATE_OF_RDAP_DATABASE\x10\n" +
	"\x12*\n" +
	"&RDAP_EVENT_ACTION_REGISTRAR_EXPIRATION\x10\v\x120\n" +
	",RDAP_EVENT_ACTION_ENUM_VALIDATION_EXPIRATION\x10\f*\xb7\x04\n" +
	"\n" +
	"RDAPStatus\x12\x17\n" +
	"\x13RDAP_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12RDAP_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14RDAP_STATUS_INACTIVE\x10\x02\x12\x19\n" +
	"\x15RDAP_STATUS_VALIDATED\x10\x03\x12 \n" +
	"\x1cRDAP_STATUS_RENEW_PROHIBITED\x10\x04\x12!\n" +
	"\x1dRDAP_STATUS_UPDATE_PROHIBITED\x10\x05\x12#\n" +
	"\x1fRDAP_STATUS_TRANSFER_PROHIBITED\x10\x06\x12!\n" +
	"\x1dRDAP_STATUS_DELETE_PROHIBITED\x10\a\x12\x15\n" +
	"\x11RDAP_STATUS_PROXY\x10\b\x12\x17\n" +
	"\x13RDAP_STATUS_PRIVATE\x10\t\x12\x17\n" +
	"\x13RDAP_STATUS_REMOVED\x10\n" +
	"\x12\x18\n" +
	"\x14RDAP_STATUS_OBSCURED\x10\v\x12\x1a\n" +
	"\x16RDAP_STATUS_ASSOCIATED\x10\f\x12\x16\n" +
	"\x12RDAP_STATUS_LOCKED\x10\r\x12\x1e\n" +
	"\x1aRDAP_STATUS_PENDING_CREATE\x10\x0e\x12\x1d\n" +
	"\x19RDAP_STATUS_PENDING_RENEW\x10\x0f\x12 \n" +
	"\x1cRDAP_STATUS_PENDING_TRANSFER\x10\x10\x12\x1e\n" +
	"\x1aRDAP_STATUS_PENDING_UPDATE\x10\x11\x12\x1e\n" +
	"\x1aRDAP_STATUS_PENDING_DELETE\x10\x122\\\n" +
	"\n" +
	"RDAPLookup\x12$\n" +
	"\bLookupIP\x12\x06.ip.IP\x1a\x10.ip.RDAPResponse\x12(\n" +
	"\n" +
	"LookupCIDR\x12\b.ip.CIDR\x1a\x10.ip.RDAPResponseB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_rdap_proto_rawDescOnce sync.Once
	file_proto_ippb_rdap_proto_rawDescData []byte
)

func file_proto_ippb_rdap_proto_rawDescGZIP() []byte {
	file_proto_ippb_rdap_proto_rawDescOnce.Do(func() {
		file_proto_ippb_rdap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_rdap_proto_rawDesc), len(file_proto_ippb_rdap_proto_rawDesc)))
	})
	return file_proto_ippb_rdap_proto_rawDescData
}

var file_proto_ippb_rdap_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_ippb_rdap_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ippb_rdap_proto_goTypes = []any{
	(RDAPIPVersion)(0),   // 0: ip.RDAPIPVersion
	(RDAPRole)(0),        // 1: ip.RDAPRole
	(RDAPEventAction)(0), // 2: ip.RDAPEventAction
	(RDAPStatus)(0),      // 3: ip.RDAPStatus
	(*RDAPEntity)(nil),   // 4: ip.RDAPEntity
	(*RDAPEvent)(nil),    // 5: ip.RDAPEvent
	(*RDAPNetwork)(nil),  // 6: ip.RDAPNetwork
	(*RDAPResponse)(nil), // 7: ip.RDAPResponse
	(*IP)(nil),           // 8: ip.IP
	(*CIDR)(nil),         // 9: ip.CIDR
}
var file_proto_ippb_rdap_proto_depIdxs = []int32{
	1, // 0: ip.RDAPEntity.roles:type_name -> ip.RDAPRole
	2, // 1: ip.RDAPEvent.action:type_name -> ip.RDAPEventAction
	0, // 2: ip.RDAPNetwork.ip_version:type_name -> ip.RDAPIPVersion
	3, // 3: ip.RDAPNetwork.status:type_name -> ip.RDAPStatus
	4, // 4: ip.RDAPNetwork.entities:type_name -> ip.RDAPEntity
	5, // 5: ip.RDAPNetwork.events:type_name -> ip.RDAPEvent
	6, // 6: ip.RDAPResponse.network:type_name -> ip.RDAPNetwork
	8, // 7: ip.RDAPLookup.LookupIP:input_type -> ip.IP
	9, // 8: ip.RDAPLookup.LookupCIDR:input_type -> ip.CIDR
	7, // 9: ip.RDAPLookup.LookupIP:output_type -> ip.RDAPResponse
	7, // 10: ip.RDAPLookup.LookupCIDR:output_type -> ip.RDAPResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_ippb_rdap_proto_init() }
func file_proto_ippb_rdap_proto_init() {
	if File_proto_ippb_rdap_proto != nil {
		return
	}
	file_proto_ippb_ip_proto_init()
	file_proto_ippb_cidr_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_rdap_proto_rawDesc), len(file_proto_ippb_rdap_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ippb_rdap_proto_goTypes,
		DependencyIndexes: file_proto_ippb_rdap_proto_depIdxs,
		EnumInfos:         file_proto_ippb_rdap_proto_enumTypes,
		MessageInfos:      file_proto_ippb_rdap_proto_msgTypes,
	}.Build()
	File_proto_ippb_rdap_proto = out.File
	file_proto_ippb_rdap_proto_goTypes = nil
	file_proto_ippb_rdap_proto_depIdxs = nil
}
