// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ippb/subnet.proto

package ippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subnet describes the network portion of a CIDR block. It is
// intentionally permissive: callers may supply a numeric prefix length
// (the canonical form), a textual netmask, or the full CIDR text
// fragment ("/24") and let downstream code reconcile.
type Subnet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Format:
	//
	//	*Subnet_Text
	//	*Subnet_PrefixLength
	//	*Subnet_Netmask
	Format        isSubnet_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subnet) Reset() {
	*x = Subnet{}
	mi := &file_proto_ippb_subnet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subnet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subnet) ProtoMessage() {}

func (x *Subnet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ippb_subnet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subnet.ProtoReflect.Descriptor instead.
func (*Subnet) Descriptor() ([]byte, []int) {
	return file_proto_ippb_subnet_proto_rawDescGZIP(), []int{0}
}

func (x *Subnet) GetFormat() isSubnet_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *Subnet) GetText() string {
	if x != nil {
		if x, ok := x.Format.(*Subnet_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Subnet) GetPrefixLength() uint32 {
	if x != nil {
		if x, ok := x.Format.(*Subnet_PrefixLength); ok {
			return x.PrefixLength
		}
	}
	return 0
}

func (x *Subnet) GetNetmask() string {
	if x != nil {
		if x, ok := x.Format.(*Subnet_Netmask); ok {
			return x.Netmask
		}
	}
	return ""
}

type isSubnet_Format interface {
	isSubnet_Format()
}

type Subnet_Text struct {
	// "/N" or "N" prefix length string.
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Subnet_PrefixLength struct {
	// Prefix length in bits. 0..32 for v4, 0..128 for v6.
	PrefixLength uint32 `protobuf:"varint,2,opt,name=prefix_length,json=prefixLength,proto3,oneof"`
}

type Subnet_Netmask struct {
	// Dotted-decimal netmask for IPv4 ("255.255.255.0").
	Netmask string `protobuf:"bytes,3,opt,name=netmask,proto3,oneof"`
}

func (*Subnet_Text) isSubnet_Format() {}

func (*Subnet_PrefixLength) isSubnet_Format() {}

func (*Subnet_Netmask) isSubnet_Format() {}

var File_proto_ippb_subnet_proto protoreflect.FileDescriptor

const file_proto_ippb_subnet_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ippb/subnet.proto\x12\x02ip\"k\n" +
	"\x06Subnet\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12%\n" +
	"\rprefix_length\x18\x02 \x01(\rH\x00R\fprefixLength\x12\x1a\n" +
	"\anetmask\x18\x03 \x01(\tH\x00R\anetmaskB\b\n" +
	"\x06formatB1Z/github.com/accretional/proto-ip/proto/ippb;ippbb\x06proto3"

var (
	file_proto_ippb_subnet_proto_rawDescOnce sync.Once
	file_proto_ippb_subnet_proto_rawDescData []byte
)

func file_proto_ippb_subnet_proto_rawDescGZIP() []byte {
	file_proto_ippb_subnet_proto_rawDescOnce.Do(func() {
		file_proto_ippb_subnet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ippb_subnet_proto_rawDesc), len(file_proto_ippb_subnet_proto_rawDesc)))
	})
	return file_proto_ippb_subnet_proto_rawDescData
}

var file_proto_ippb_subnet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ippb_subnet_proto_goTypes = []any{
	(*Subnet)(nil), // 0: ip.Subnet
}
var file_proto_ippb_subnet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ippb_subnet_proto_init() }
func file_proto_ippb_subnet_proto_init() {
	if File_proto_ippb_subnet_proto != nil {
		return
	}
	file_proto_ippb_subnet_proto_msgTypes[0].OneofWrappers = []any{
		(*Subnet_Text)(nil),
		(*Subnet_PrefixLength)(nil),
		(*Subnet_Netmask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ippb_subnet_proto_rawDesc), len(file_proto_ippb_subnet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ippb_subnet_proto_goTypes,
		DependencyIndexes: file_proto_ippb_subnet_proto_depIdxs,
		MessageInfos:      file_proto_ippb_subnet_proto_msgTypes,
	}.Build()
	File_proto_ippb_subnet_proto = out.File
	file_proto_ippb_subnet_proto_goTypes = nil
	file_proto_ippb_subnet_proto_depIdxs = nil
}
